#Training args
model_name_or_path: YOUR_PATH/unsup-Qwen3-8B-datav3-only_mask_w_item
hub_model_id: YOUR_PATH/admissionTask-unsup-Qwen3-8B-datav3-only_mask_w_item
torch_dtype: bfloat16
use_lora: true
quantization: null
gradient_checkpointing: true
force_auto_device_map: false
use_flash_attention: true
deepspeed: train_configs/deepspeed_zero2.json
auto_find_batch_size: true

output_dir: models/admissionTask-unsup-Qwen3-8B-datav3-only_mask_w_item
overwrite_output_dir: true
load_best_model_at_end: false
metric_for_best_model: eval_f1_macro
greater_is_better: true
save_strategy: "steps"
save_steps: 2
save_only_model: false
save_total_limit: 2

# evaluation
do_train: true
do_eval: false
do_predict: false
eval_strategy : "steps"
eval_steps: 20

per_device_train_batch_size: 64
per_device_eval_batch_size: 16
gradient_accumulation_steps: 1

# optimizer settings
optim: adamw_torch
learning_rate: 0.0003
weight_decay: 0.001
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
adam_epsilon: 0.0000001

# lora settings
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_modules:
  - all

# reporting
logging_strategy: steps
logging_first_step: true
logging_steps: 20
report_to: wandb
run_name: "admissionTask-unsup-Qwen3-8B-datav3-only_mask_w_item"
disable_tqdm: false

# hub settings
push_to_hub: false
resume_from_checkpoint: false

# performance
bf16: true
fp16: false
torch_compile: false
ddp_find_unused_parameters: false